# Basic experiment settings
experiment:
  name: exp1
  base_output_dir: outputs
  check_val_every_n_epoch: 1
  save_top_k: 3

# Model configuration
model:
  name: ConvNeXtV2Tiny # Tiny, Pico, Nano, Base, Huge
  loss_name: CrossEntropy
  lr: 0.0001
  device: cuda 

# Dataset configuration
data:
  dataset_name: load_isic2016
  num_classes: 2
  train_batch_size: 32
  test_batch_size: 32
  val_batch_size: 32
  test_size: 0.2
  cache_dir: .cache
  dataset_kwargs:
    preprocessor: 
      name: BasicImagePreprocessor
      img_size: 224
    train_csv_path: data/ISBI2016_ISIC_Part3_Training_GroundTruth.csv
    train_img_dir: data/ISBI2016_ISIC_Part3_Training_Data
    train_img_col: ISIC_0000000
    train_target_col: benign
    test_csv_path: data/ISBI2016_ISIC_Part3_Test_GroundTruth.csv
    test_img_dir: data/ISBI2016_ISIC_Part3_Test_Data/ISBI2016_ISIC_Part3_Test_Data
    test_img_col: ISIC_0000003
    test_target_col: '0.0'

# Training configuration
trainer:
  seed: 42
  devices: 1
  accelerator: gpu
  accumulate_grad_batches: 4
  log_every_n_steps: 30
  max_epochs: 30
  gradient_clip_val: 1
  precision: 16-mixed
  enable_progress_bar: true

# Metrics configuration
metrics:
  task: binary  # multiclass, multilabel, binary
  average: macro
  include_precision: true
  include_recall: true