#Randomweightsampler weightloss

# Cài đặt thí nghiệm cơ bản
# Phần này định nghĩa các tham số tổng thể của thí nghiệm, như tên, thư mục đầu ra, tần suất kiểm tra validation, và số lượng mô hình tốt nhất cần lưu.
experiment:
  name: exp1 # Tên của thí nghiệm để nhận dạng.
  base_output_dir: outputs # Thư mục cơ bản nơi lưu đầu ra (như checkpoint mô hình).
  check_val_every_n_epoch: 1 # Thực hiện validation mỗi 1 epoch.
  save_top_k: 3 # Lưu top 3 mô hình tốt nhất dựa trên metrics validation.

# Cấu hình mô hình
# Phần này cấu hình kiến trúc mô hình, hàm loss, learning rate, và thiết bị chạy.
model:
  name: ConvNeXtV2Tiny # Kiến trúc mô hình sử dụng; tùy chọn: Tiny, Pico, Nano, Base, Huge.
  loss_name: CrossEntropy # Tên hàm loss; ở đây là CrossEntropy cho phân loại.
  lr: 0.0001 # Learning rate cho optimizer.
  device: cuda # Thiết bị chạy mô hình; 'cuda' cho GPU.
  loss_kwargs: # Các tham số bổ sung cho hàm loss.
    weight: [0.597, 3.078] # Trọng số lớp cho weighted loss để xử lý lệch dữ liệu: trọng số thấp hơn cho lớp đa số (benign, class 0), cao hơn cho lớp thiểu số (malignant, class 1).

# Cấu hình dataset
# Phần này thiết lập việc tải dataset, kích thước batch, phân chia, và tiền xử lý.
data:
  dataset_name: load_isic2018 # Tên hàm tải dataset cho ISIC2018.
  num_classes: 2 # Số lượng lớp: 2 (phân loại nhị phân, ví dụ: benign vs. malignant).
  train_batch_size: 32 # Kích thước batch cho data loader huấn luyện.
  test_batch_size: 32 # Kích thước batch cho data loader kiểm tra.
  val_batch_size: 32 # Kích thước batch cho data loader validation.
  test_size: 0.2 # Tỷ lệ dữ liệu dùng cho test/validation (20%).
  cache_dir: .cache # Thư mục để cache dữ liệu đã xử lý.
  train_sampler: # Sampler cho dữ liệu huấn luyện để xử lý lệch lớp.
    name: WeightedRandomSampler # Sử dụng WeightedRandomSampler để oversample lớp thiểu số.
    replacement: true # Lấy mẫu với thay thế để cho phép oversampling.
    # Trọng số sẽ được tính tự động: 1 / số lượng mẫu của lớp cho từng mẫu để oversample lớp thiểu số.
  dataset_kwargs: # Các tham số bổ sung cho việc khởi tạo dataset.
    preprocessor: # Bộ tiền xử lý cho hình ảnh.
      name: BasicImagePreprocessor # Tên lớp preprocessor.
      img_size: 224 # Resize hình ảnh về 224x224 pixel.
    train_csv_path: data/ISIC2018_Task3_Training_GroundTruth/ISIC2018_Task3_Training_GroundTruth/ISIC2018_Task3_Training_GroundTruth.csv # Đường dẫn file CSV huấn luyện.
    train_img_dir: data/ISIC2018_Task3_Training_Input # Thư mục chứa hình ảnh huấn luyện.
    train_img_col: image # Tên cột trong CSV cho tên file hình ảnh.
    train_target_col: [MEL, BCC] # Các cột trong CSV chỉ lớp positive (malignant: MEL hoặc BCC).
    test_csv_path: data/ISIC2018_Task3_Test_GroundTruth/ISIC2018_Task3_Test_GroundTruth/ISIC2018_Task3_Test_GroundTruth.csv # Đường dẫn file CSV kiểm tra.
    test_img_dir: data/ISIC2018_Task3_Test_Input # Thư mục chứa hình ảnh kiểm tra.
    test_img_col: image # Tên cột trong CSV cho tên file hình ảnh kiểm tra.
    test_target_col: [MEL, BCC] # Các cột trong CSV cho lớp positive kiểm tra.

# Cấu hình trainer
# Phần này cấu hình trainer, bao gồm phần cứng, logging, và siêu tham số huấn luyện.
trainer:
  seed: 42 # Seed ngẫu nhiên để đảm bảo tính lặp lại.
  devices: 1 # Số lượng thiết bị (GPU) sử dụng.
  accelerator: gpu # Loại accelerator: 'gpu' cho huấn luyện trên GPU.
  accumulate_grad_batches: 4 # Tích lũy gradient qua 4 batch trước khi cập nhật trọng số (batch hiệu quả lớn hơn).
  log_every_n_steps: 30 # Ghi metrics mỗi 30 bước.
  max_epochs: 30 # Số lượng epoch tối đa để huấn luyện.
  gradient_clip_val: 1 # Clip gradient đến giá trị này để tránh exploding gradients.
  precision: 16-mixed # Sử dụng mixed precision training (16-bit) để huấn luyện nhanh hơn và tiết kiệm bộ nhớ.
  enable_progress_bar: true # Hiển thị thanh tiến trình trong quá trình huấn luyện.

# Cấu hình metrics
# Phần này định nghĩa cách tính metrics, như loại nhiệm vụ và metrics cần include.
metrics:
  task: binary # Loại nhiệm vụ phân loại: binary (nhị phân.
  average: macro # Phương pháp trung bình cho metrics: macro (trung bình không trọng số giữa lớp).
  include_precision: true # Include metrics precision trong đánh giá.
  include_recall: true # Include metrics recall trong đánh giá.
